### ISSUE TITLE
Wsvvrijheid - Club Page

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#102]
Club page in the current site: https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/club/index.js

**Tasks**

**Services**
- [x] Create `getArtCategories` and `useArtCategories` in `libs/utils/src/services/category`
  _This functions should return all the categories that are related to approved arts. We want to allow user to be able to filter the arts by category._ 
- [x] Skip `useAuth` for now. You can use auth as `const auth = { user: null, isLoggedIn: false, token: null }`
- [x] Create service instead of collection query `useCollections` and `getAllCollections` in `libs/utils/src/services/collection`
- [x] Create `useArts` in typescript. 
_(This seems a bit complex. It can fetch arts by category, by artist name or art title, page etc)_

**Hooks**
- [x] Move [useChangeParams](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/hooks/useChangeParams.js) hook to `libs/ui/src/hooks` _(It can be improved)_

**Components**
- [x] Create `CategoryFilterSkeleton`  and its story in `libs/ui/src/components/CategoryFilter`
- [x] Create `ArtClubSidebar` component in `libs/ui/src/components/ArtsSidebar` and create story for it
- [x] Create `ArtClubTemplate` and create story for it
