### ISSUE TITLE
Wsvvrijheid - Collection Dynamic Page

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#104]
Current page: https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/club/collection/%5Bslug%5D.js

**Tasks**

- [ ] Use `CollectionBook` component in monorepo for `Collection`
- [ ] Create services `getCollection` and `getCollectionPaths` in `libs/utils/src/services/collection`
- [ ] You can create `CollectionTemplate` without the Layout like we have done for other templates.
