### ISSUE TITLE
Create tables and forms for `Category` and `Tag`

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#1057]
**Tasks**

- [x] Create table columns in `packages/ui/src/data/tables`
 - Include the columns in `useColumns`
- [x] Create form schemas in `packages/ui/src/data/schemas`
 - Include the new schemas in `useSchemas`
- [x] Add Categories and Tags to sidebar menu
- [x] Add `tags` and `categories` to `actionRolesEndpoints` (Make the roles the same as activities)
- [x] Make sure StrapiEndpoint has categories and tags
- [ ] Test create/update/delete/publish category and tag

> NOTE: Schema is being used for form validation. Fields are being used to render the form items. You can explore ModelCreateForm and ModelEditForm to see how the fields are used there.
