### ISSUE TITLE
Admin - Sidebar

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#112]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1150%3A12569

**Tasks**

**1. AdminNavItem**
- [ ] Create AdminNav components in `libs/ui/src/admin/AdminNav` and  AdminNav folder includes 
 - `AdminNavItem.tsx`
 - `AdminNavItem.stories.tsx`
 - `AdminNav.tsx`
 - `AdminNav.stories.tsx`
 - `types.ts`
 - `index.ts`
- [ ] Create AdminNavItem component. If menu has submenu, the component can be an [`Accordion`](https://chakra-ui.com/docs/components/accordion/usage) or the best using [`Collapse Transition`](https://chakra-ui.com/docs/components/transitions/usage#collapse-transition)
- [ ] Nav Buttons are ghosts variant with `gray.500` color _(active button ise `colorScheme='primary'`)_

>  - [ ] **Bonus:** You can investigate how to change `colorScheme` based on the current link with `next/router` (active state)

```ts
export type AdminNavItemProps = {
  label: string
  link: string
  submenu?: NavItemProps[]
} & ButtonProps // This will allow us to use `leftIcon` and other chakra props
```

**2. AdminNav**
You can create a navItems array to render `NavItemProps` in a map. 

```tsx
const navItems = [
  {
    label: 'Dashboard',
    link: '/',
    icon: MdOutlineSpaceDashboard
  },
  // ... other menu items
]
```

**3. AdminSidebar**
- [ ] Create AdminSidebar component in `libs/ui/src/admin/AdminSidebar`. Use AdminNav in the sidebar component
- [ ] Sidebar is a `Stack` with props `w={300} py={8} px={4} bg="white" spacing={8}`
