### ISSUE TITLE
Admin Collection Table

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#157]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1230%3A11972

**Tasks**

- [ ] Create page folder in `apps/admin/pages/arts/collections/index.tsx`
- [ ] Create CollectionTable in `libs/ui/src/admin/Tables/CollectionTable` (just like ArtsTable)
- [ ] Show these columns in the table (image, title, description, arts (length), translationStatus)
- [ ] Use CollectionTable in collection page
