### ISSUE TITLE
ArtAddToCollectionCard

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#189]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1274%3A12306

<img width="1021" alt="Screenshot 2022-09-26 at 13 04 47" src="https://user-images.githubusercontent.com/22167684/192260958-54857ea3-ff84-47ab-950f-21aa59ce40e9.png">

**Tasks**

- [ ] Create ArtAddToCollectionCard component in `libs/ui/src/admin/ArtAddToCollectionCard` folder
- [ ] Title should always be single line `noOfLines={1}`
- [ ] Show remove button if `isAdded` prop is true.
- [ ] Add `onAdd` and `onRemove` props
- [ ] View button will open `ArtDetailsModal`
- [ ] Create story file with `isAdded` state. Change the state with `onAdd` and `onRemove` props
