### ISSUE TITLE
Topics Page

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#193]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1296%3A12494

**Tasks**

- [ ] Update `NewsCard` design and rename to `TopicCard`
- [ ] Prevent users from re-recommending
- [ ] Fetch all arts and do frontend filtering
- [ ] User can search by title, description and publisher
- [ ] Implement sorting by date
