### ISSUE TITLE
Fix Bugs

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#194]
- [x] Password field initially should be hidden
- [x] Signup: Some characters (_+-=) are not considered as special characters. (@yhtyyar94) e505fd29b0a2219d682923156dcf95fba85dd5d9
- [ ] Avatar images not showing(profile and artist page).
- [x] Auth doesn't seem to be loaded after registering (@7alip) 07fc702b3866eb4842ab47e528302a25d4bca058
- [ ] Forgot passoword should be shown in only kunsthalte project. Hide forgot password link from other projects (until we find proper way of creating link for it) (@7alip)
- [x] Sing with google should only be shown in kunsthalte project. Provider redirects to wsvvrijheid, we need to change it (@7alip)
- [x] Fix wsvvrijheid logo (@7alip) 2dc42cc89e187544c2efad2c7910fdca0341d151
- [x] Platforms images are missing in /platforms page (@zahirekrem09 )(#232)
- [x] Cookie drawer / popup (@zahirekrem09 )(#231 )
- [x] In ContentMaker News page when user clicks `view` button, open page in a new popup instead of tab (@yhtyyar94) (#239)
- [x] Fix Add bookmark issue in ContentMaker News page (@yhtyyar94) (#240)
