### ISSUE TITLE
Collection Edit Form

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#196]
[Prototype](https://www.figma.com/proto/5ISnHleV0FIN8YJHYpHZpL/WSVVrijheid?page-id=1693%3A16230&node-id=2231%3A29934&viewport=445%2C-905%2C0.17&scaling=scale-down&starting-point-node-id=2231%3A29934&show-proto-sidebar=1)

[Design](https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1309%3A12828)

**Tasks**

- [ ] Use Accordion to collapse the form
- [ ] Image and FileUploader size (300x350)
- [ ] Delete should trigger WConfirm alert
