### ISSUE TITLE
Collection Add Arts Modal

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#197]
[Prototype](https://www.figma.com/proto/5ISnHleV0FIN8YJHYpHZpL/WSVVrijheid?page-id=1693%3A16230&node-id=2231%3A24659&viewport=445%2C-905%2C0.17&scaling=scale-down&starting-point-node-id=2231%3A24659&show-proto-sidebar=1) (Click Add Arts To Collection Button)

[Design](https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1310%3A16758)

**Tasks**

Blocked by #189 

- [ ] Store selected art ids in state (initial state should be existing arts in the collection)
- [ ] Change ArtAddToCollectionCard state (isAdded) if art is exist in the collection (Show remove button)
- [ ] `Add +x Arts` button should update collection
  - Discuss about translation relations after mutation
