### ISSUE TITLE
WSelect Async

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#211]
AsyncSelect

The async select component will be used across the app in various places. For example when we create art, we need collection list in select, when we create hashtag, we need mention list in select. These lists should be fetched from api.

We use [ChakraReactSelect](https://github.com/csandman/chakra-react-select) in our WSelect component.

**Tasks**

- [ ] Investigate if we can adjust WSelect to support async
- [ ] Otherwise we might create WAsyncSelect similar to WSelect
- [ ] Create story for it (use real api data: `api/mentions`, `api/categories` etc)

**Comment by 7alip** [comment]
We can reopen if necessary
