### ISSUE TITLE
Samen Twitter Search

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#237]
**Tasks**

- [ ] Create custom `search` route  in **mention** model (refer to mention.search controller)
- [ ] Create custom `search` controller in **mention** model (use mention.search service in it)
- [ ] Create custom `search` service in **mention** model (use twitterApi that we created in apps/api/src/libs folder)

> NOTE: controllers returns response `ctx.send(...)` and are used for routes. But services returns result `return result`. That's why we use services in controller and also we can call them from anywhere we need.

You can use params (`/api/mentions/search/:username`) or query (`/api/mentions/search?username=...`) approach.

Remember we can use this `mention.search` service somewhere else.

```ts
const twiterUser = strapi.services("api::mention.mention").search(username)
```

**How to test the endpoint?**

After implementing the new `search` route, it should appear in Strapi model. You may need to allow this route from Strapi panel. Otherwise you may get `401 or 403 auth error`. See the image below

You can allow from `Settings/API Token/Token/Mention` and `Settings/Roles/Authenticated/Mention`
(Its easier to allow public roles from `Settings/Roles/Public/Mention`, so that you don't need token for the request)

After you allow this new route `http://localhost:1337/api/mentions/search?username=samenvvv` should give some result.

<img width="1220" alt="Screenshot 2022-11-03 at 06 42 22" src="https://user-images.githubusercontent.com/22167684/199654812-53679895-143c-4a3c-9fbf-3f5665876a26.png">
