### ISSUE TITLE
Admin | NewsCardBase

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#37]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=806%3A9983

![Image](https://user-images.githubusercontent.com/22167684/183307418-dd52b1cf-d3c2-447b-8850-305e0ee2dffe.png)

**Tasks**

- [x] Create component in `libs/ui/src/admin/NewsCard`
- [x] Component has 2 variants: `horizontal`, `vertical`
- [ ] Horizontal variant should always look like vertical variant in small viewports.
- [x] Description should be able to be hidden
- [ ] Open the news in a new small window instead of iframe.
