### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#383]
Design: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=1703%3A13955&t=o9ok1g7G0WcTtqbG-0

**Tasks:**

- [x] Update samenvvv homepage design: `apps/samenvvv/pages/index.tsx`
- [x] Update translations in `public/locales/<locale>/common.json`
- [ ] Bonus: You can adjust `HashtagCard` component design
- [x] You can use `<Button size="lg">` for buttons.
- [x] We use theme colors from `libs/config/src/theme/colors`. You can use color shades as `color=primary.500`.  These are primary colors for each project: (foundation -  blue | kunsthalte - green | admin - green | samenvvv - samen)

**NOTE: Do not change header design in this task**

![samen-desktop](https://user-images.githubusercontent.com/22167684/216958051-ac178fde-0284-4956-a7e8-b7df81b02964.png)

**Comment by 7alip** [comment]
@bllakcn, The issue description has been updated. You are welcome to ask any questions.
