### ISSUE TITLE
Admin | ArtApprovalModal

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#4]
This modal will be triggered when an editor clicks on an ArtCard.

Design link: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=802%3A10309

![Image](https://user-images.githubusercontent.com/22167684/183307547-ef10469a-c38d-421e-9b29-26b7adc9b053.png)

**Tasks**

- [ ] Create component in folder `libs/ui/src/admin/ArtApprovalModal`
- [ ] Create `ArtApprovalForm` component in separate file in the same folder.
- [ ] Image must be `objectFit='contain'`, because editor should always be able to see whole image.
- [ ] All actions should be given via props
  -  onReject - onApprove - onDelete
  - onReject and onApprove mutations should receive `art id, feedback, editor id` parameters.
- [ ] Create a component story and just show window.alert for each mutation. Just put a button in the story to open ArtApprovalModal
