### ISSUE TITLE
Add zoom image feature to WImage

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#49]
We want to have generic zoomable image component. For now it's going to be used in ArtApprovalModal but we may use it somewhere else too.

I found an example repo. https://github.com/rpearce/react-medium-image-zoom. But there are many alternatives. You need to find a <ins>NextImage compatible zoom library</ins>. Otherwise you can use ChakraImage _(`import { Image } from '@chakra-ui/react'`)_ for zoom option in WImage. <ins>**Make a conclusion with @MustafaTRKYLMZ about which library will meet our needs  before starting implementation.**</ins>

**Tasks**

- [x] Extend `WImage` component with zoom feature. Activate zoom option if `hasZoom` prop is provided.
- [x] Make sure if the zoom library is compatible with NextImage. We use NextImage in `WImage`. If the zoom library won't work with NextImage you should investigate to fix the problem. Two possibilities to fix it: 
  1. Find NextImage compatible zoom library
  2. Use ChakraImage 
- [x] Add `Zoom` option in `WImage.stories.tsx`
- [x] Update ArtApprovalModal with zoom feature
- [x] Add Grid example in story
