### ISSUE TITLE
Onboarding | Chakra Breakpoint & React Query

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#52]
Desing: https://www.figma.com/file/2KeHIr9IOh0HoCO89akiLn/WsvvUI?node-id=974%3A12136

> This issue is prepared in the branch [feat/example-chakra-react-query](https://github.com/wsvvrijheid/monorepo/tree/feat/example-chakra-react-query). You need to rename the branch by adding your username before creating a pull request.

**Tasks**

**1. Chakra Playground**
- [ ] Pull the branch `origin/feat/example-chakra-react-query` 
(`git checkout -q --track origin/feat/example-chakra-react-query`)
- [ ] Rename the branch with your username: 
`git branch -m feat/example-chakra-react-query feat/example-chakra-react-query-<username>`
- [ ] Button sizes are `md` (default) in desktop and `lg` in small devices. 
_(Keep in mind, responsive styling are only valid for plain css attributes, like width, margin, color etc. `size` is a custom non-css chakra prop. You can use [useBreakpointValue](https://chakra-ui.com/docs/hooks/use-breakpoint-value) to make non-css props responsive. 
`const size = useBreakpointValue({ base: "md", lg: "lg" })` or  
`const size = useBreakpointValue(["md", null, null, "lg"])`_ 
- [ ] `onSend` action should be passed through prop. You will be testing `onSend` action in story.
- [ ] Alert component will be shown after the form is submitted (error or success statuses).

**2. React Query**
- [ ] Review how react-query useMutation is used in `ChakraBreakpointReactQueryExample.stories.tsx`
