### ISSUE TITLE
Wsvvrijheid | Platforms Page

### ISSUE THREAD

**Issue by zahirekrem09** [wsvvrijheid/monorepo#67]
Design: https://wsvvrijheid.nl/platforms

- [The old site's Platforms page](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/platforms/index.js) will be migrated to the new repo as typescript.
- Platforms will be taken from the Strapi and listed.

See the template is created `libs/ui/templates/PlatformTemplate` and how it is used in `apps/foundation/pages/platform/[code]`. You should do the similar thing.

 **Clicking on each card will go to the relevant detail page**
- [ ] academy
- [ ] samenvvv
- [ ] lotus
- [ ] art-stop

**TODOS**
- [ ] Convert [platform/inde.js](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/platforms/index.js) to `libs/ui/templates/PlatformsTemplate/PlatformsTemplate.tsx` <ins>**without Layout**</ins>
- [ ] Create `PlatformsTemplate.stories.tsx` and test it with 
- [ ] Create `apps/foundation/pages/platform/index.tsx` and put your PlatformsTemplate inside Layout
