### ISSUE TITLE
Wsvvrijheid | Art Dynamic Page

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#74]
Design: https://wsvvrijheid.nl/club/art/snow-1

- [The old site's single art page](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/club/art/[slug].js) will be written in TS.

See the template is created `libs/ui/templates/PlatformTemplate` and how it is used in `apps/foundation/pages/platform/[code]`. You should do the similar thing.

**TODOS**
- [ ] Convert [club/art/[slug].js](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/club/art/[slug].js) to `libs/ui/templates/ArtTemplate/ArtTemplate.tsx` <ins>**without Layout**</ins>
- [ ] Write `useGetArts` in TS and move to `libs/utils/src/services/art/getBySlug.ts`
  - I included other arts (by category) into the current art like `{ ...art, arts, . . . }`. But it will be cleaner if you separate them out in different files (`getArtBySlug` and `getArtsByCategory`).
  - So I would move `getArtsByCategory` in a separate file and also I would add `useArtsByCategory` query in it. In the component you will fetch current art and category arts with different queries.
  - You should also prefetch getArtsByCategory in `getStaticProps`
- [ ] **Don't include `useViewArt` in this issue.**
- [ ] Create `ArtTemplate.stories.tsx`. _(Story might not work if we can provide `router.query.slug` in the story in a proper way. So just create a query and we will figure out how can we provide router later)_
- [ ] Create `apps/foundation/pages/club/art/[slug].tsx` and put your `ArtsTemplate` inside Layout
- [ ] Write `getArtPaths` function in TS and move it to `libs/utils/src/services/art/getStaticPaths.ts`. _(Platforms service is an example)_
- [ ] You can test if the page is working by running `yarn start`
