### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#755]
We have CookieBanner component. You need to adjust this component.

**Tasks**

- [x] Remove ` onClose, onAllow, onReject` props and handle `onAllow` process inside the component
- [x] To read and write cookies use `import { useCookie } from 'react-use'` or `import { getCookie, setCookie } from 'cookies-next'`
- [x] If user clicks `Allow` button, we will save it to cookie and won't show it to the same user again. (If `cookiesAccepted` value is true, return null)
- [x] The component should be fixed at the bottom of the page. Adjust styles.
- [x] Add CookieBanner component to `_app.tsx` for each app.
- [x] Fix translations
