### ISSUE TITLE
Add platform in modeleditform in volunteers page 

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#762]
**Tasks**

- [ ] Add Platform relation to Volunteer model in Strapi
- [ ] Adjust volunteer type
- [ ] Add `Platform` select to Volunteer edit form (ModelEditForm) (fields, schema)
- [ ] Show platform name in Volunteer table (columns)

<img width="1173" alt="Screenshot 2023-08-15 at 23 53 32" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/06e71ef2-97df-474a-86bd-b78077436dcd">
