### ISSUE TITLE
Donation list

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#768]
Add donations page to Dashboard app.

**Tasks**

- [ ] Add Donations link to admin nav
- [ ] Donation link should be visible only for `admin` role
- [ ] Create `donations.tsx` file in `apps/dashboard/pages` dir.
- [ ] Create `donationColumns` in `packages/ui/data/table` dir
- [ ] Use `DataTable` component on the page (See arts and [model] pages)
- [ ] Display following columns:
  - email
  - amount
  - status
  - date (createdAt)
