### ISSUE TITLE
Wsvvrijheid | Join

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#78]
Move [Join Page](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/join.js) from wsvvrijheid to monorepo
URL: https://wsvvrijheid.nl/join

**Tasks**

- [ ] Use [PlatformList.tsx](https://github.com/wsvvrijheid/monorepo/blob/main/apps/foundation/components/PlatformList/PlatformList.tsx) component for [project-list.js](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/components/projects-list.js) _(Project is renamed to Platform)_
- [ ] Use [JoinForm](https://github.com/wsvvrijheid/monorepo/blob/main/libs/ui/src/components/JoinForm/JoinForm.tsx) from ui components
- [ ] Create `JoinTemplate` in `libs/ui/templates/JoinTemplate/JoinTemplate.tsx`. Move [join.js](https://github.com/wsvvrijheid/wsvvrijheid/blob/develop/src/pages/join.js) page to JoinTemplate **without Layout** _(Layout will be wrapper in `apps/foundation/pages/join.tsx`)_
- [ ] Create `JoinTemplate.stories.tsx`. _Your mutations and queries should be inside the template. You can test them in story before using the template in app's `join.tsx` page._

---

**Bonus:**

```ts
 const projectsQuery = useQuery({
  queryKey: 'projects',
  queryFn: () => request({ url: `api/projects` }),
})
```

You can move it to services as `getPlatforms` and `usePlatforms` in `libs/utils/services/platform/getAll.ts`
