### ISSUE TITLE
Refactor isAdminMode (security)

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#816]
We use `isAdminMode` cookie, which enables post-sentence management without any authentication. This is an important security issue. Anyone can update/delete/add sentences with the cookie.

<img width="745" alt="Screenshot 2023-09-04 at 13 07 48" src="https://github.com/wsvvrijheid/monorepo/assets/22167684/725883fd-a94c-46ce-b366-5c2d237d3ca3">

**Todos**

- [x] Remove `isAdminMode` from hashtag page props and everywhere
- [x] Add login page for samenvvv project
 - No header link needed, only `/login` route
- Use `AuthProvider` the same way we use in admin project
- [x] Only `admin` roles can see `<PostSentencesModal />`
 - `session.user.roles.includes('admin')` 
- [x] Only `admin` roles can use `/api/kv/hashtag-sentences` api route
 - Use `withIronSessionApiRoute` (see api/auth/user)
