### ISSUE TITLE
Add `notes` field to the course application form.

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/monorepo#899]
Add `notes` field to the course application form.

Sometimes we need to make a note about an application. For example, pay half the fee. 
We may want to need to know the payment details or some other informations. 

![image](https://github.com/wsvvrijheid/monorepo/assets/58182269/05b9ec57-59c9-448a-bf46-7ca4ef15923b)

___

**Tasks**

- [x] Add `notes` long string field to CourseApplication table in Strapi
- [x] Update CourseApplicaiton type with the new field
- [x] Add this field to `useCourseApplicationSchema` and `useCourseApplicationFields` (type=textarea)

> NOTE: Schema is being used for form validation. Fields are being used to render the form items. You can expolore `ModelCreateForm` and `ModelEditForm` to see how the fields are used there.
