### ISSUE TITLE
Generate tweets from a content with VercelAI

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/monorepo#928]
**Tasks**

- [x] Investigate how to use [VercelAI](https://sdk.vercel.ai/docs) and streaming responses
- [x] Compare ai models in the [Vercel playground](https://sdk.vercel.ai)
- [x] Create Nextjs API route (See documentation)
- [x] Create a component with Textarea and submit button. Send the content with your prompt to get tweets in JSON format
- [x] GPT should respond in JSON format. Parse the response and list underneath the Textarea form

Examples: https://vercel.com/templates/ai
